@startuml Use Case Diagram
skinparam packageStyle rectangle
left to right direction

:Admin:
:Instructor:
:Student:


rectangle CodeGrader {

  (Login)
  (Add Submission Feedback)
  (Download Course Grades)
  (Create Instructor Account)
  (Create Course)
  (Create Student Account)
  (Upload Test Case)
  (Create Assignment)
  (Update Assignment)
  (Submit Assignment)
  (View Course Grades)


  (Download Course Grades) ..> (View Course Grades) : extends

  (Add Submission Feedback) ..> (View Course Grades) : extends

  (Create Assignment) ..> (Upload Test Case) : uses
  (Update Assignment) ..> (Upload Test Case) : uses

}



:Admin: --> (Login)
:Admin: --> (Create Instructor Account)

(Login) <-- :Instructor:
(Create Course) <-- :Instructor:
(Create Student Account) <-- :Instructor:
(Upload Test Case) <-- :Instructor:
(Create Assignment) <-- :Instructor:
(Update Assignment) <-- :Instructor:
(View Course Grades) <-- :Instructor:
(Download Course Grades) <-- :Instructor:
(Add Submission Feedback) <-- :Instructor:

:Student: --> (Login)
:Student: --> (Submit Assignment)



@enduml
