@startuml Use Case Diagram
skinparam packageStyle rectangle
left to right direction

:Admin:
:Instructor:
:Student:


rectangle CodeGrader {

  (Upload Test Case)
  (Update Assignment)
  (Create Assignment)
  (View Course Grades)
  (Download Course Grades)
  (Add Submission Feedback)
  (Create Instructor Account)
  (Create Course)
  (Delete Instructor Account)
  (Login)
  (Edit Instructor Account)
  (Create Student Account)
  (Edit Course)
  (Edit Student Account)
  (Delete Student Account)
  (Delete Course)
  (Submit Assignment)
  (View Test Case)




  (Download Course Grades) ..> (View Course Grades) : extends

  (Add Submission Feedback) ..> (View Course Grades) : extends

  (Delete Student Account) ..> (View Course Grades) : extends

  (Create Assignment) ..> (Upload Test Case) : uses
  (Update Assignment) ..> (Upload Test Case) : uses

}



:Admin: --> (Login)
:Admin: --> (Create Instructor Account)
:Admin: --> (Delete Instructor Account)
:Admin: --> (Edit Instructor Account)

(Login) <-- :Instructor:
(Create Course) <-- :Instructor:
(Create Student Account) <-- :Instructor:
(Upload Test Case) <-- :Instructor:
(Create Assignment) <-- :Instructor:
(Update Assignment) <-- :Instructor:
(View Course Grades) <-- :Instructor:
(Download Course Grades) <-- :Instructor:
(Add Submission Feedback) <-- :Instructor:
(Edit Course) <-- :Instructor:
(Delete Course) <-- :Instructor:
(Delete Student Account) <-- :Instructor:
(Edit Student Account) <-- :Instructor:

:Student: --> (Login)
:Student: --> (Submit Assignment)
:Student: --> (View Test Case)



@enduml
