@startuml Use Case Diagram
skinparam packageStyle rectangle
left to right direction

:Administrator:
:Instructor:
:Student:


rectangle CodeGrader {

  (Login)
  (Create Instructor Account)
  (Create Student Account)
  (Create Course)
  (Create Assignment)
  (View Assigned Assignments)
  (View Course Assignments)
  (Submit Assignments)
  (View Submission Results)
  (View Submission History)
  (Provide Submission Feedback)
  (View Submission Feedback)
  (View Course Grades)
  (Download Student Information)
  (Upload Test Case)

  (Create Assignment) ..> (Upload Test Case) : uses
  (Download Student Information) ..> (View Course Grades) : extends
}
Administrator ---> (Login)
Administrator ---> (Create Instructor Account)
(Login) <--- Instructor
(Create Student Account) <--- Instructor
(Create Course) <--- Instructor
(Create Assignment) <--- Instructor
(View Submission Results) <--- Instructor
(View Submission History) <--- Instructor
(View Course Assignments) <--- Instructor
(View Submission Feedback) <--- Instructor
(Provide Submission Feedback) <--- Instructor
(View Course Grades) <--- Instructor
(Download Student Information) <--- Instructor
(Upload Test Case) <--- Instructor
Student ---> (Login)
Student ---> (View Submission History)
Student ---> (View Submission Results)
Student ---> (Submit Assignments)
Student ---> (View Submission Feedback)
Student ---> (View Assigned Assignments)



@enduml
